### ISSUE TITLE
potential issues in chm13.draft_v1.0.fasta identified by using another independent assembly

### ISSUE THREAD

**Issue by cschin** [marbl/CHM13-issues#1] opened 2021-02-27 15:34 UTC
I generate an assembly with Peregrine2021 (0.4.1, main:eb7a2dc+) and find it may be useful for identifying some potential issues in the current T2T assembly although it may be equally likely to be issues in my assembly results.

- Method summary:
  - Generate independent assembly (not using T2T’s overlaps and graphs to avoid ascertainment biases)
  - Try to separate the assembly results to two haplotypes assembly-wise
  - Call variants with dipcall, generate a VCF file for the variants seen between the assembly and T2T chm13.draft_v1.0.fasta
  - Going through some dense variant call clusters and check if there are alignment anomaly manually
- For the pick 10 regions picked, four have nearby low coverage alignment signal from the bed files. Six do not. The alignment files in the IGV used are from markerandlength.idxsession (from Arang, the polishing team):
- I don’t have a systematic to generate a bed from from the VCF files that I have. However, if anyone is interesting, I can provide the VCF file.

Regions:
chr1:132,379,149-132,387,405
chr2:91,194,176-91,258,718
chr9:65,106,334-65,426,773
chr9:68,183,834-68,263,943
chr9:74,317,466-74,319,968
chr10:37,180,330-37,252,004
chr11:18,996,964-19,068,834
chr12:35,546,839-35,617,750
chr13:9,812,837-9,873,599
chr16:42,993,455-43,044,690

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391719-5c791500-78cd-11eb-9203-2fbe82f32822.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391723-6864d700-78cd-11eb-8690-7a5914b6110d.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391724-6b5fc780-78cd-11eb-8bf2-53047cf56467.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391726-6e5ab800-78cd-11eb-82c1-342ae3cc1353.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391729-71ee3f00-78cd-11eb-8814-d8f44edc9067.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391732-74509900-78cd-11eb-84b0-2f0a637ac0c7.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391734-77e42000-78cd-11eb-8c1f-24e6d4a1bbc2.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391746-8c281d00-78cd-11eb-8f31-f8b14fc6c0dd.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391751-90ecd100-78cd-11eb-90bc-27906666e10b.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1320747/109391754-93e7c180-78cd-11eb-9753-17d42ae8a3fa.png">

**Comment by arangrhie** [comment] 2021-03-09 16:52
Thanks, @cschin for the heads up!

I've added regions flagged by clipped reads, and seems like all 9 regions you posted are now included except chr9:74,317,466-74,319,968. This region (chr9:74,317,466-74,319,968) is a het with 2 SVs (INS as you see from your screenshot) with some het SNPs around. I'll post the het sites sometimes this week, still needs a bit of a clean up.

Does your vcf contain potential corrections?
Besides the hets, we are gathering suggested fixes in a vcf format.
Would be good to include yours as candidates too.

**Comment by cschin** [comment] 2021-03-09 17:08
@arangrhie  Thanks.  Just some quick answers to your questions,

"Does your vcf contain potential corrections?", it may contain some sequences, but my assembly also need additional validation to be treated as "corrections". 

"Besides the hets, we are gathering suggested fixes in a vcf format.", 

per the answer above, my VCF is generated as the different between my ("haplotype" resolved) assembly to the T2T references, the generated VCF file is useful identifying the differences between the assemblies and we may use it to semi-automatic tagging additional problematic regions in CHM13 draft and check if the alternative assembly may be correct in those regions. 

If we have some evidence that the alternative assembled sequences (directly from hifiasm, hiCanu or my peregrine-pro-2021 assembler) are correct, we can patch it but I am not sure if it a simple work to validate that though.

"Would be good to include yours as candidates too."  I am doing it manually now as it will takes time to develop a tool for this. I checked a couple more case last weekend. I can send it over. As it is done manually, it is far from systematic and as a comprehensive list.

**Comment by arangrhie** [comment] 2021-04-29 05:11
Hi @cschin , it actually turned out an issue with winnowmap v1.11 ~ v2.0.
We confirmed the excessive clipping did not reproduce with [v2.01](https://github.com/marbl/Winnowmap/releases/tag/v2.01) from [simulated reads](https://github.com/marbl/CHM13-issues/tree/main/v1.0/simulated). Now, all 'issues' are either associated with sequencing biases in hifi (Low_GA/TC or Low_AT) or true consensus error (Low_Qual or Low).
Please refer to the latest hifi.pri.issues.bed track for 'known' issues.

In addition, we found default minimap2 repetitive minimizer filtering introduced mismapping due to minimizer dropouts in highly repetitive region. This might have introduced mismappings in your alignments used in the benchmark. If it was using minimap2, set `-f 0` or try the latest winnowmap.

**Comment by arangrhie** [comment] 2022-04-12 20:02
Closing this for now as all issues have been addressed for v1.0-v1.1

**Closed as completed by arangrhie** 2022-04-12 20:02 UTC
